CREATE DATABASE appointment;

CREATE USER appointment_user WITH PASSWORD 'appointment_password';

ALTER DATABASE appointment OWNER TO appointment_user;

GRANT ALL PRIVILEGES ON DATABASE appointment TO appointment_user;

\c appointment

CREATE TABLE public.patient (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.specialty (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.medic (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    specialty_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (specialty_id) REFERENCES public.specialty(id)
);

CREATE TABLE public.room (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.appointment_time (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timeslot VARCHAR(10) NOT NULL,
    "date" DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.appointment (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medic_id INT NOT NULL,
    patient_id INT NOT NULL,
    room_id INT NOT NULL,
    appointment_time_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (medic_id) REFERENCES public.medic(id),
    FOREIGN KEY (patient_id) REFERENCES public.patient(id),
    FOREIGN KEY (room_id) REFERENCES public.room(id),
    FOREIGN KEY (appointment_time_id) REFERENCES public.appointment_time(id)
);

INSERT INTO public.specialty (name) VALUES
    ('Cardiology'),
    ('Dermatology'),
    ('Neurology'),
    ('Pediatrics'),
    ('Psychiatry');

 INSERT INTO public.medic (name, specialty_id) VALUES
    ('Dr. John Smith', 1),
    ('Dr. Emily Johnson', 2),
    ('Dr. Michael Brown', 3),
    ('Dr. Sarah Davis', 4),
    ('Dr. David Wilson', 5),
    ('Dr. Laura Martinez', 1),
    ('Dr. James Anderson', 2),
    ('Dr. Jennifer Lee', 3),
    ('Dr. Robert Taylor', 4),
    ('Dr. Jessica Thomas', 5);

 INSERT INTO public.patient (name) VALUES
    ('Alice Johnson'),
    ('Bob Smith'),
    ('Charlie Brown'),
    ('David Wilson'),
    ('Eve Davis');

INSERT INTO public.room (number) VALUES
    (101),
    (102),
    (103),
    (104),
    (105);

INSERT INTO public.appointment_time (timeslot, "date") VALUES
    ('09:00', '2024-06-01'),
    ('10:00', '2024-06-01'),
    ('11:00', '2024-06-01'),
    ('14:00', '2024-06-01'),
    ('15:00', '2024-06-01'),
    ('09:00', '2024-06-02'),
    ('10:00', '2024-06-02'),
    ('11:00', '2024-06-02'),
    ('14:00', '2024-06-02'),
    ('15:00', '2024-06-02'),
    ('09:00', '2024-06-03'),
    ('10:00', '2024-06-03'),
    ('11:00', '2024-06-03'),
    ('14:00', '2024-06-03'),
    ('15:00', '2024-06-03');

GRANT USAGE ON SCHEMA public TO appointment_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO appointment_user;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO appointment_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO appointment_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO appointment_user;

CREATE UNIQUE INDEX appointment_medic_id_idx ON public.appointment (medic_id,appointment_time_id);
CREATE UNIQUE INDEX appointment_room_id_idx ON public.appointment (room_id,appointment_time_id);
CREATE UNIQUE INDEX appointment_patient_id_idx ON public.appointment (patient_id,appointment_time_id);
