INSERT INTO specialty (name) VALUES
    ('Cardiology'),
    ('Dermatology'),
    ('Neurology'),
    ('Pediatrics'),
    ('Psychiatry');

 INSERT INTO medic (name, specialty_id) VALUES
    ('Dr. John Smith', 1),
    ('Dr. Emily Johnson', 2),
    ('Dr. Michael Brown', 3),
    ('Dr. Sarah Davis', 4),
    ('Dr. David Wilson', 5),
    ('Dr. Laura Martinez', 1),
    ('Dr. James Anderson', 2),
    ('Dr. Jennifer Lee', 3),
    ('Dr. Robert Taylor', 4),
    ('Dr. Jessica Thomas', 5);

 INSERT INTO patient (name) VALUES
    ('Alice Johnson'),
    ('Bob Smith'),
    ('Charlie Brown'),
    ('David Wilson'),
    ('Eve Davis'),
    ('Frank Miller'),
    ('Grace Lee'),
    ('Hannah Taylor'),
    ('Ian Anderson'),
    ('Jack Thomas'),
    ('Karen Martinez'),
    ('Liam Robinson'),
    ('Mia Clark'),
    ('Noah Lewis'),
    ('Olivia Walker'),
    ('Paul Hall'),
    ('Quinn Allen'),
    ('Ryan Young'),
    ('Sophia Hernandez'),
    ('Tyler King'),
    ('Uma Scott'),
    ('Victor Green'),
    ('Wendy Adams'),
    ('Xander Baker'),
    ('Yara Nelson'),
    ('Zachary Carter'),
    ('Ava Mitchell'),
    ('Benjamin Perez'),
    ('Chloe Roberts'),
    ('Daniel Turner'),
    ('Ella Phillips'),
    ('Finn Campbell'),
    ('Gabriella Parker'),
    ('Henry Evans'),
    ('Isabella Edwards'),
    ('Jackie Collins'),
    ('Kylie Stewart'),
    ('Landon Morris'),
    ('Madison Rogers'),
    ('Nathan Reed'),
    ('Olivia Cook'),
    ('Peyton Morgan'),
    ('Quinn Bell'),
    ('Riley Murphy'),
    ('Sophia Bailey'),
    ('Tyler Rivera'),
    ('Victoria Cooper'),
    ('William Richardson'),
    ('Xavier Cox'),
    ('Yasmine Howard'),
    ('Zoe Ward'),
    ('Aiden Flores'),
    ('Brooklyn Simmons'),
    ('Caleb Foster'),
    ('Daisy Gonzales'),
    ('Ethan Bryant'),
    ('Fiona Alexander'),
    ('Gavin Russell'),
    ('Hailey Griffin'),
    ('Isaac Diaz'),
    ('Jasmine Hayes'),
    ('Kaden Myers'),
    ('Lily Ford'),
    ('Mason Hamilton'),
    ('Natalie Graham'),
    ('Owen Sullivan'),
    ('Penelope Wallace'),
    ('Quentin West'),
    ('Riley Cole'),
    ('Savannah Jenkins'),
    ('Tristan Perry'),
    ('Ulysses Powell'),
    ('Violet Long'),
    ('Wyatt Patterson'),
    ('Ximena Hughes'),
    ('Yosef Flores'),
    ('Zara Simmons'),
    ('Avery Foster'),
    ('Brody Gonzales'),
    ('Cora Bryant'),
    ('Declan Alexander'),
    ('Elena Russell'),
    ('Felix Griffin'),
    ('Gabrielle Diaz'),
    ('Harrison Hayes'),
    ('Isla Myers'),
    ('Jaxon Ford'),
    ('Kinsley Hamilton'),
    ('Leo Graham'),
    ('Mila Sullivan'),
    ('Nolan Wallace'),
    ('Olive West'),
    ('Parker Cole'),
    ('Quinn Jenkins'),
    ('Ryder Perry'),
    ('Sienna Powell'),
    ('Theo Long'),
    ('Uma Patterson'),
    ('Vance Hughes'),
    ('Willow Flores');

INSERT INTO room (number) VALUES
    (101),
    (102),
    (103),
    (104);

INSERT INTO appointment_time (timeslot, date) VALUES
    ('09:00', '2024-06-01'),
    ('10:00', '2024-06-01'),
    ('11:00', '2024-06-01'),
    ('14:00', '2024-06-01'),
    ('15:00', '2024-06-01'),
    ('09:00', '2024-06-02'),
    ('10:00', '2024-06-02'),
    ('11:00', '2024-06-02'),
    ('14:00', '2024-06-02'),
    ('15:00', '2024-06-02'),
    ('09:00', '2024-06-03'),
    ('10:00', '2024-06-03'),
    ('11:00', '2024-06-03'),
    ('14:00', '2024-06-03'),
    ('15:00', '2024-06-03');

DROP INDEX IF EXISTS appointment_medic_id_idx;
DROP INDEX IF EXISTS appointment_room_id_idx;
CREATE UNIQUE INDEX appointment_medic_id_idx ON appointment (medic_id,appointment_time_id);
CREATE UNIQUE INDEX appointment_room_id_idx ON appointment (room_id,appointment_time_id);